# Pod example without Consul
apiVersion: v1
kind: Pod
metadata:
  name: counting-minimal-pod
  labels:
    app: counting-service
spec:
  containers:
    - name: counting-service
      image: topfunky/counting-service:0.0.1
      ports:
      - containerPort: 9001
---
apiVersion: v1
kind: Service
metadata:
  name: counting-minimal-load-balancer
spec:
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 9001
  selector:
    app: counting-service
  type: LoadBalancer
